apiVersion: v1
kind: Service
metadata:
  name: microservizio-crud-service
spec:
  type: NodePort
  selector:
    app: microservizio-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
